version: '2.1'

volumes:
    database_data:
        driver: local

services:
    front:
      build: .
      ports:
        - "80:80"
        - "443:443"
        - "9000:9000"
      links:
        - mysql:mysql
      volumes:
        - ./www/default:/var/www
        - ./sites:/etc/nginx/conf.d
        - ./logs:/var/log/supervisor

    mysql:
      image: mysql
      ports:
        - "3306:3306"
      volumes:
          - database_data:/var/lib/mysql
          - ./mysql:/home
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: database_name
        MYSQL_USER: user
        MYSQL_PASSWORD: password
